Loris-Test9:	Dimension.o Image.o ImageNG.o MyQT.o Couleur.o ImageRGB.o ImageB.o Exception.o ExceptionRGB.o XYException.o ArrayList.o Iterateur.o Traitements.o
				g++ Test9.cpp -o Loris-Test9 MyQT.o Image.o ImageNG.o Dimension.o Couleur.o ImageRGB.o ImageB.o Exception.o ExceptionRGB.o XYException.o ArrayList.o Iterateur.o Traitements.o -lSDL -lpthread -Wl,-O1 -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Core.so /usr/lib64/libGL.so

Dimension.o:	Dimension.cpp Dimension.h
				g++ Dimension.cpp -c

Image.o:		Image.cpp Image.h
				g++ Image.cpp -c

ImageNG.o:		ImageNG.cpp ImageNG.h
				g++ ImageNG.cpp -c

MyQT.o:			MyQT.cpp MyQT.h
				g++ -c MyQT.cpp -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++


Couleur.o:		Couleur.cpp Couleur.h
				g++ Couleur.cpp -c

ImageRGB.o:		ImageRGB.cpp ImageRGB.h
				g++ ImageRGB.cpp -c

ImageB.o:		ImageB.cpp ImageB.h
				g++ ImageB.cpp -c

Exception.o:	Exception.cpp Exception.h
				g++ Exception.cpp -c

ExceptionRGB.h:	ExceptionRGB.cpp ExeptionRGB.h
				g++ ExceptionRGB.cpp -c

XYException.o:	XYException.cpp XYException.h
				g++ XYException.cpp -c

ArrayList.o:	ArrayList.cpp ArrayList.h
				g++ ArrayList.cpp  -c

Iterateur.o:	Iterateur.cpp Iterateur.h
				g++ Iterateur.cpp -c

Traitements.o:	Traitements.cpp Traitements.h
				g++ Traitements.cpp -c

clean:
		rm -f *.o

clobber:	clean
		rm -f Loris-Test9